Likelion-YeungNam-Univ/12th-gibble-web

gible/.gitignore, gible/craco.config.js, gible/jsconfig.json, gible/package-lock.json, gible/package.json, gible/src/App.js, gible/src/api/authAxios.js, gible/src/api/axios.js, gible/src/config/api.js, gible/src/index.js, gible/src/store/authSlice.js, gible/src/store/store.js
인증이 필요하지 않은 요청과 인증이 필요한 요청 전역 api 인스턴스 구분
- .env 파일 추가 - `BASE_URL` 환경변수 설정
- config/api.js 파일에 환경변수 `apiServer` 설정
- 인증 필요 요청(Authorization 헤더 필요)의 경우 리덕스의 store에서 accessToken을 추가
- 401 에러 발생(토큰 만료) 시 refreshToken을 통한 토큰 재발급 및 요청 재전송
- refreshToken을 통한 새로운 accessToken 발급 api 생성 필요
- 카카오 소셜 로그인 API 등록 필요
- craco 패키지 설치 : 경로 입력 별칭(alias) 지정 - `@/*`
=> HF-68: api 전역 인스턴스 분류

gible/src/components/signup/step02/InformationBox.js
아이디가 아닌 이메일로 수정해달라는 백엔드의 요청이 있어서 수정 후 다시 PR 올립니다!
=> HF-54: 아이디 삭제, 이메일로 교체

gible/src/api/login/loginResponseHandler.js, gible/src/store/authSlice.js
loginHandler 수정
- redux state에서 refreshToken 삭제
- 로그인 요청 시 request body에서 cilentId 삭제
=> HF-50: loginHandler 수정 - refreshToken 삭제, request body clientId 삭제

.github/workflows/ci.yml
=> TEST: cicd 테스트

src/api/donation/getMyDonation.js, src/api/donation/getReceivedDonation.js
기부 페이지 API 작성
- `getMyDonation` : 내가 기부한 게시글의 정보 불러오기
- `getReceivedDonation` : 나에게 기부해 준 사람들의 목록 불러오기
=> HF-61: 기부 API 작성

src/App.js, src/components/common/Separator.js, src/components/review/PageController.js, src/components/review/ReviewCard.js, src/pages/post/Post.js, src/pages/review/Review.js
리뷰(투명 후기) 목록 페이지 작성
- 페이지 컨트롤러 관련 기능은 api를 통해 데이터를 받아온 후 페이지네이션을 다같이 구현하는게 나을 것 같아서 일단 ui만 넣어놓은 상태입니다.
- 공톹 컴포넌트 `Separator` 변경 - `Input`, `Button` 공통 컴포넌트 생성에 따른 구조 변화
=> HF-99: 리뷰 목록 페이지 작성

src/App.js, src/api/authAxios.js, src/components/common/Separator.js, src/components/review/PageController.js, src/components/review/ReviewCard.js, src/pages/post/Post.js, src/pages/review/Review.js
refreshToken 전달 방법 변경(쿠키를 통한 전달)으로 인한 불필요 코드 삭제
`authAxios()` 내 `store`에서 refreshToken을 가져와 재발급받는 코드 삭제
=> HF-68: refreshToken 전달 방법 변경(쿠키를 통한 전달)으로 인한 불필요 코드 삭제

src/api/donation/getMyDonation.js, src/api/donation/getReceivedDonation.js, src/api/mypage/getDelivery.js, src/api/mypage/getMyPage.js, src/api/mypage/getMyPosts.js, src/api/mypage/getParticipation.js, src/api/review/getReview.js
- 로그인이 필요한 `GET` 요청들 `apiClient -> authAxios`로 수정
=> Refact: 로그인이 필요한 API 수정

src/components/post/post/Content.js, src/layouts/header/Navbar.js
- 아직 처리되지 않은 네비게이션 기능 추가
- 커뮤니티 기부글 목록 페이지 -> 기부글 작성 페이지 네비게이션
- 네비게이션 바 커뮤니티 -> 기부글 목록 페이지
=> feat: 일부 라우팅, 네비게이션 기능 추가

src/api/login/loginResponseHandler.js, src/api/signup/signupHandler.js, src/components/signup/step02/InformationForm.js, src/store/authSlice.js
로그인 응답 상태코드 510일 시 email 저장을 위한 수정
redux state 설정 수정
=> HF-81: 로그인 응답 상태코드 510일 시 email 저장을 위한 수정

src/App.js, src/components/post/newPostComplete/Content.js, src/components/post/newPostComplete/NewPostComplete.js, src/components/post/newPostComplete/Notice.js, src/components/post/newPostComplete/Title.js
**개요**
기부 게시글 목록페이지 작성
투명후기 구성과 같은 컴포넌트로 구현했습니다. 
**구현**
=> HF-113 : 기부 게시글 완료 페이지 완료

src/api/authAxios.js, src/api/login/logoutHandler.js, src/layouts/header/HeadComponent.js
authAxios() 내 apiServer import 경로 수정
=> HF-114: authAxios() 내 apiServer import 경로 수정

src/api/post/deletePost.js, src/api/post/donatePost.js, src/api/post/getDonators.js, src/api/post/modifyPost.js, src/api/post/reportPost.js, src/api/post/showPost.js, src/api/post/showPostList.js, src/api/post/uploadPost.js, src/components/login/Redirection.js, src/components/post/newPost/PostForm.js, src/components/post/post/DonationBar.js, src/components/post/post/PostCard.js, src/components/post/post/PostList.js, src/layouts/header/HeadComponent.js
- POST 관련 API 작성
- 전체 authAxios 사용
- 게시물 업로드 API 연결
- 게시물 조회 API 연결
=>  HF-61: 일부 API 연결 및 useEffect Dependency 작성

package-lock.json, package.json, src/firebase/firebaseConfig.js, src/pages/review/NewReview.js, src/pages/review/ReviewPage.js, src/store/store.js
이미지 업로드 시 firbase storage로 이미지 업로드 후 url 사용을 위한 firebase 기본 설정
- firebase 패키지 설치
- firebaseConfig.js 작성
- 이미지 업로드 시 참고를 위한 임시 코드 작성(NewReview.js 내 주석 처리)
- 기본적으로 파일 업로드 시 403 에러가 발생하여 파이어베이스 스토리지 룰에서 요청을 모두 액세스하도록 설정해놓은 상태입니다.
=> HF-118: firebase 설정

src/api/post/showPostList.js, src/components/post/post/Content.js, src/components/post/post/PageController.js, src/components/post/post/PostCard.js, src/components/post/post/PostList.js
기부 요청 게시글 페이지네이션 구현
pageable 응답 값을 이용한 페이지네이션 구현
=> HF-119: 게시글 페이지네이션 구현

src/components/review/reviewPage/ReviewInfo.js, src/pages/review/ReviewPage.js
리뷰 상세 페이지 구현
ReivewPage.js 수정
api 연결 필요
=> feat: 리뷰 상세 페이지 생성

src/components/post/newPost/PostForm.js, src/components/review/newReview/ReviewForm.js
- 글자 수 초과 시 즉시 경고 메시지 출력
- `PostForm`, `ReviewForm` 모두 설정
=> HF-111: 글자 수 초과시 즉시 경고메시지 출력

src/components/mypage/Event.js
=> feat: 이벤트 날짜=> 제목으로 변경

src/components/main/Community.js, src/components/main/Review.js, src/components/main/YellowBloodIntro.js
=> HF123: 메인페이지 스타일 수정 

src/components/post/post/PostCard.js, src/components/post/post/PostCategory.js
- NEW 표시 기능 추가
- 게시글 카테고리 글씨체 굵기 수정
=> HF-62: NEW 표시 기능 추가

src/App.js, src/components/post/post/NoticeCard.js, src/components/post/post/PostList.js, src/components/post/postPage/Content.js, src/components/post/postPage/DonorBox.js, src/components/post/postPage/DonorCard.js, src/components/post/postPage/Title.js, src/pages/post/NoticePage.js
- 공지 사항 추가
- DonorBox 가장 오른쪽은 구분선 표시 안되게 설정
- 숫자에 따라 간격이 바뀌는 현상 수정
=> HF-62: 공지 사항 추가, DonorBox 수정

src/api/mypage/getMyPosts.js, src/api/review/newReview.js, src/assets/svg/goto.svg, src/components/review/Content.js, src/components/review/newReview/Modal.js, src/components/review/newReview/ReviewForm.js, src/components/review/reviewPage/GoToMyPost.js, src/components/review/reviewPage/ReviewInfo.js, src/pages/review/CompleteReview.js, src/pages/review/ReviewPage.js
- 리뷰-게시글 연동 : 리뷰 내에서 작성 게시물로 이동 버튼 추가
- 리뷰 작성 완료 후 '리뷰 바로가기' 버튼 링크 추가
=> HF-125: 리뷰-게시글 연동 및 리뷰 작성 후 작성 리뷰로 이동

src/api/event/searchEvent.js, src/api/review/searchReview.js, src/components/review/Seperator.js, src/pages/event/EventList.js, src/pages/review/Review.js
- 리뷰 검색
- 이벤트 검색
- `PageController`, `게시글 번호` 가 검색에 맞게 렌더링 되지 않음. 수정 필요
=> HF-124: 리뷰, 이벤트 검색 기능 추가

src/components/common/PageNotice.js, src/components/common/Separator.js, src/components/post/newPost/FormNotice.js, src/components/post/newPost/InputFormFix.js, src/components/post/post/DonationBar.js, src/components/post/post/NoticeCard.js, src/components/post/post/PageController.js, src/components/post/post/PostCard.js, src/layouts/header/HeadComponent.js, src/layouts/header/Navbar.js, src/pages/post/Post.js
=> HF-129: 디자인 수정 post 페이지, 상세페이지 

src/components/review/newReview/Error.js, src/components/review/newReview/FormNotice.js, src/components/review/newReview/InputFormFix.js, src/components/review/newReview/ReviewForm.js, src/pages/review/NewReview.js
=> HF-132: 리뷰 작성 폼 수정
